

## Data Preparation

Loading data

```{r}
library(readr)
library(tidyverse)

paste0_named = function(names, ...) setNames(paste0(...), names)

union_cen = read_csv("../../data-raw/Union/cen_union_army_whites_csv.csv", cols(.default = "c"))
colnames(union_cen) = union_cen[1,]
CEN_wide = union_cen[2:nrow(union_cen), ]

union_msr = read_csv("../../data-raw/Union/msr_union_army_whites_csv.csv", cols(.default = "c"))
colnames(union_msr) = union_msr[1,]
MSR_wide = union_msr[2:nrow(union_msr), ]
```

Preparing data from the 1900 census. Includes matching recruits and their family members.

```{r}
variable_stems = c(
  name = "nam",
  birth_year = "byr", # Only for 1900
  birth_month = "bmo", # Only for 1900
  gender = "gen",
  birth_place = "bpl"
)

recruit_uid_variable = c(unique_id = "recidnum")
recruit_variables_0 = paste0_named(names(variable_stems), "rec", variable_stems, "_0")
fam_uid_variable = c(unique_id = NULL)
fam_variables_0 = lapply(1:15, function(i) {
  fam_number_id = formatC(i, width = 2, flag = "0")
  paste0_named(names(variable_stems), "h", variable_stems, fam_number_id, "_0")
})

recruit_data = CEN_wide %>% select(!!!recruit_variables_0, !!!recruit_uid_variable)
fam_data = lapply(1:15, function(i) {
  df = CEN_wide %>% select(!!!fam_variables_0[[i]]) %>% mutate(unique_id = NA)
})

CEN = rbind(
  recruit_data,
  do.call(rbind, fam_data)
) %>% 
  drop_na(., starts_with("name")) %>%
  extract(
    name, 
    into = c("last_name", "first_name", "middle_name", "comments"), 
    regex = "\\s*(\\w+)\\s*,?\\s*(\\w+)(?:\\s*(\\w+))?\\s*(?:\\((.+)\\))?",
    remove = FALSE
  ) %>% 
  mutate_if(is.character, ~na_if(., ''))
```

Preparing data from military service records.

```{r}
variables = c(
  unique_id = "recidnum",
  name = "recname1",
  birth_date = "rb_date1",
  birth_place = "rb_stat1",
  enlistment_age = "lstag1_1",
  enlistment_date = "lstdt1_1"
)

MSR = MSR_wide %>% 
  select(!!!variables) %>% 
  mutate(    
    enlistment_year = case_when(
      is.na(enlistment_date) ~ NA,
      str_detect(substr(enlistment_date, 1, 4), "\\d{4}") ~ as.integer(substr(enlistment_date, 1, 4)),
      TRUE ~ NA
    ),
    est_birth_year = enlistment_year - as.integer(enlistment_age) 
  ) %>% 
  mutate(
    birth_year = case_when(
      is.na(birth_date) | str_detect(birth_date, "^----") ~ NA,
      TRUE ~ as.integer(substr(birth_date, 1, 4))
    ),
    birth_month = case_when(
      is.na(birth_date) | str_detect(birth_date, "^.{4}--") ~ NA,
      TRUE ~ as.integer(substr(birth_date, 5, 6))
    ),
    birth_day = case_when(
      is.na(birth_date) | str_detect(birth_date, "--$") ~ NA,
      TRUE ~ as.integer(substr(birth_date, 7, 8))
    )
  ) %>% 
  mutate(
    unified_birth_year = ifelse(is.na(birth_year), est_birth_year, birth_year)
  ) %>% 
  drop_na(., starts_with("name")) %>%
  extract(
    name, 
    into = c("last_name", "first_name", "middle_name", "comments"), 
    regex = "\\s*(\\w+)\\s*,?\\s*(\\w+)(?:\\s*(\\w+))?\\s*(?:\\((.+)\\))?",
    remove = FALSE
  ) %>% 
  mutate_if(is.character, ~na_if(., ''))
```


```{r}
MSR %>% 
  group_by(birth_place) %>% 
  summarise(count=n()) %>% 
  arrange(-count)

MSR %>% 
  group_by(lname_1 = substr(last_name, 1, 1)) %>% 
  summarise(count=n()) %>% 
  arrange(-count)
```

## Linkage

```{r}
library(comparator)

compareRecords2 <- function(df1, df2, fields, comparators, breaks_list) {
  bin_comps = lapply(1:length(fields), function(k) {
    comparator = comparators[[k]]
    field = fields[k]
    breaks = breaks_list[[k]]
    
    dmat = comparator::pairwise(lev, df1[, field, drop=T], df2[, field, drop=T], return_matrix=TRUE)
    comparisons = cut(dmat, breaks=breaks, labels=seq_len(length(breaks)-1))
    I = 1:length(comparisons)
    J = as.numeric(comparisons)
    non_NAs = !is.na(J)
    bin_comp = Matrix::sparseMatrix(i=I[non_NAs], j=J[non_NAs], x=TRUE, dims=c(length(comparisons), nlevels(comparisons)))
    
    return(bin_comp)
  })
  
  return(list(
    comparisons = as.matrix(do.call(cbind, bin_comps)),
    n1 = nrow(df1),
    n2 = nrow(df2),
    nDisagLevs = sapply(bin_comps, ncol),
    compFields = data.frame(file1=fields, file2=fields, types=sapply(comparators, class))
  ))
}
```


```{r}
library(BRL)
library(tidyverse)
library(FScoreBRL)

df1 = MSR %>% 
  transmute(
    first_name = first_name, 
    fname_1 = substr(first_name, 1, 1),
    #fname_2 = substr(first_name, 2, 1000L),
    last_name = last_name, 
    lname_1 = substr(last_name, 1, 1),
    middle_name = middle_name, 
    birth_year = as.numeric(unified_birth_year),
    unique_id = str_remove(unique_id, "^0+"),
    birth_place = birth_place
  ) %>% 
  mutate_if(is.character, ~na_if(., '')) %>% 
  filter(birth_place=="MI")

df2 = CEN %>% 
  transmute(
    first_name = first_name, 
    fname_1 = substr(first_name, 1, 1),
    #fname_2 = substr(first_name, 2, 1000L),
    last_name = last_name, 
    lname_1 = substr(last_name, 1, 1),
    middle_name = middle_name, 
    birth_year = as.numeric(birth_year),
    unique_id = ifelse(is.na(unique_id), paste0("FAM_", 1:length(unique_id)), str_remove(unique_id, "^0+")),
    birth_place = birth_place
  ) %>% 
  mutate_if(is.character, ~na_if(., '')) %>% 
  filter(birth_place=="MI")

if (nrow(df2) > nrow(df1)) {
  temp = df1
  df1 = df2
  df2 = temp
}

jaro = comparator::JaroWinkler(similarity=FALSE)
lev = comparator::Levenshtein(normalize=TRUE)
binary = comparator::BinaryComp()
numeric = comparator::Manhattan()

lev_breaks = c(-0.1, 0, 0.25, 0.5, 1.1)
bin_breaks = c(-0.1, 0.5, 1.1)
num_breaks = c(-1, 1, 5, 200)
compData = compareRecords2(
  df1,
  df2,
  fields = c("first_name", "last_name", "middle_name", "birth_year"),
  comparators = list(lev, lev, binary, numeric),
  breaks_list = list(lev_breaks, lev_breaks, bin_breaks, num_breaks)
)

Zchain <- bipartiteGibbs(compData, nIter=5000, seed=0)$Z[, 1000:5000]

BRL_est = FScoreBRL::linkage_estimate(type="BRL", Zchain, nrow(df1), nrow(df2))
F_est = FScoreBRL::linkage_estimate(type="F", Zchain, nrow(df1), nrow(df2))

all_ids = c(df1$unique_id, df2$unique_id)
dup_ids = all_ids[duplicated(all_ids)]

actual = rep(nrow(df1) + 1, nrow(df2))
matched_indices = which(df2$unique_id %in% dup_ids)
actual[matched_indices] = match(df2$unique_id[matched_indices], df1$unique_id)

F_metrics = FScoreBRL::metrics(F_est, actual, Zchain, nrow(df1), nrow(df2))
BRL_metrics = FScoreBRL::metrics(BRL_est, actual, Zchain, nrow(df1), nrow(df2))

data.table::rbindlist(list(F_metrics, BRL_metrics))
```


```{r}
library(BRL)
library(tidyverse)
library(FScoreBRL)

df1 = MSR %>% 
  transmute(
    first_name = first_name, 
    fname_1 = substr(first_name, 1, 1),
    #fname_2 = substr(first_name, 2, 1000L),
    last_name = last_name, 
    lname_1 = substr(last_name, 1, 1),
    middle_name = middle_name, 
    birth_year = as.numeric(unified_birth_year),
    unique_id = str_remove(unique_id, "^0+"),
    birth_place = birth_place
  ) %>% 
  mutate_if(is.character, ~na_if(., '')) %>% 
  filter(lname_1=="O")

df2 = CEN %>% 
  transmute(
    first_name = first_name, 
    fname_1 = substr(first_name, 1, 1),
    #fname_2 = substr(first_name, 2, 1000L),
    last_name = last_name, 
    lname_1 = substr(last_name, 1, 1),
    middle_name = middle_name, 
    birth_year = as.numeric(birth_year),
    unique_id = ifelse(is.na(unique_id), paste0("FAM_", 1:length(unique_id)), str_remove(unique_id, "^0+")),
    birth_place = birth_place
  ) %>% 
  mutate_if(is.character, ~na_if(., '')) %>% 
  filter(lname_1=="O")

if (nrow(df2) > nrow(df1)) {
  temp = df1
  df1 = df2
  df2 = temp
}

jaro = comparator::JaroWinkler(similarity=FALSE)
lev = comparator::Levenshtein(normalize=TRUE)
binary = comparator::BinaryComp()
numeric = comparator::Manhattan()

lev_breaks = c(-0.1, 0, 0.25, 0.5, 1.1)
bin_breaks = c(-0.1, 0.5, 1.1)
num_breaks = c(-1, 1, 5, 200)
compData = compareRecords2(
  df1,
  df2,
  fields = c("first_name", "last_name", "middle_name", "birth_year"),
  comparators = list(lev, lev, binary, numeric),
  breaks_list = list(lev_breaks, lev_breaks, bin_breaks, num_breaks)
)

Zchain <- bipartiteGibbs(compData, nIter=5000, seed=0)$Z[, 1000:5000]

BRL_est = FScoreBRL::linkage_estimate(type="BRL", Zchain, nrow(df1), nrow(df2))
F_est = FScoreBRL::linkage_estimate(type="F", Zchain, nrow(df1), nrow(df2))

all_ids = c(df1$unique_id, df2$unique_id)
dup_ids = all_ids[duplicated(all_ids)]

actual = rep(nrow(df1) + 1, nrow(df2))
matched_indices = which(df2$unique_id %in% dup_ids)
actual[matched_indices] = match(df2$unique_id[matched_indices], df1$unique_id)

F_metrics = FScoreBRL::metrics(F_est, actual, Zchain, nrow(df1), nrow(df2))
BRL_metrics = FScoreBRL::metrics(BRL_est, actual, Zchain, nrow(df1), nrow(df2))

data.table::rbindlist(list(F_metrics, BRL_metrics))
```




